[[shellcheck_plugin]]
= The Shellcheck Plugin

The Shellcheck plugin performs quality checks on your project's Shell source files using https://github.com/koalaman/shellcheck[Shellcheck] and generates reports from these checks.


[[sec:shellcheck_usage]]
== Usage

To use the Shellcheck plugin, include the following in your build script:

[source,kotlin]
----
plugins {
    id("com.felipefzdz.gradle.shellcheck")
}
----

The plugin adds a task to the project called `shellcheck` that performs the quality checks.

Note that in order to be portable and repeatable Shellcheck will run:

* Through a Docker container
* A not-yet-configurable Shellcheck version, hardcoded at v0.7.1.

This implies that no dependencies are required on the executing machine, except for Docker itself.

[[sec:shellcheck_tasks]]
== Tasks

The Shellcheck plugin adds the following task to the project:

`shellcheck`

+
Runs Shellcheck against the provided Shell source files.


See the link:{groovyDslPath}/org.gradle.api.plugins.quality.ShellcheckExtension.html[ShellcheckExtension] class in the API documentation.


[[sec:shellcheck_extension]]
=== Extension

[source,kotlin]
----
shellcheck {
    source = file("src/shellScripts")
    isIgnoreFailures = true
    isShowViolations = true
    shellcheckVersion = "v0.7.1"
}
----

* source - Folder where the shell scripts are located. It will search recursively matching `.sh`, `.bash`,
`.bash_login`, `.bash_logout`, `.bash_profile`, `.bashrc` and `.ksh` files. Matching on shell scripts with no extension
is not supported yet.
* isIgnoreFailures - Whether to allow the build to continue if there are warnings.
* isShowViolations - Whether rule violations are to be displayed on the console. Defaults to true.
* shellcheckVersion - By default "v0.7.1"

[[sec:shellcheck_customize_xsl]]
== Customizing the HTML report

The HTML report generated by the Shellcheck task can be customized using a XSLT stylesheet, for example to highlight specific errors or change its appearance:

[source,kotlin]
----
tasks.withType<Shellcheck>().configureEach {
    reports {
        xml.isEnabled = false
        txt.isEnabled = false
        html.isEnabled = true
        html.stylesheet = resources.text.fromFile("config/xsl/shellcheck-custom.xsl")
    }
}
----

XML generated report comes from `shellcheck -f checkstyle`, therefore you can get inspiration from https://github.com/checkstyle/contribution/tree/master/xsl[a sample Checkstyle stylesheet.]

TXT generated report comes from `shellcheck -f tty`.
