[[shellcheck_plugin]]
= The Shellcheck Plugin

The Shellcheck plugin performs quality checks on your project's Shell source files using https://github.com/koalaman/shellcheck[Shellcheck] and generates reports from these checks.


[[sec:shellcheck_usage]]
== Usage

To use the Shellcheck plugin, include the following in your build script:

[source,kotlin]
----
plugins {
    id("com.felipefzdz.gradle.shellcheck") version "1.3.0"
}
----

The plugin adds a task to the project called `shellcheck` that performs the quality checks.

Note that in order to be portable and repeatable Shellcheck will run:

* Through a Docker container
* A configurable Shellcheck version

This implies that no dependencies are required on the executing machine, except for Docker itself.

[[sec:shellcheck_tasks]]
== Tasks

The Shellcheck plugin a task called `shellcheck` to the project.


[[sec:shellcheck_extension]]
=== Extension

[source,groovy]
----
shellcheck {
    sources = files("src/shellScripts", "src/moreScripts")
    isIgnoreFailures = true
    isShowViolations = true
    shellcheckVersion = "v0.7.1"
    severity = "error"
    useDocker = true
    shellcheckBinary = "/usr/local/bin/shellcheck"
    installer = "brew"
}
----

* sources - Folders where the shell scripts are located. It will search recursively matching `.sh`, `.bash`,
`.bash_login`, `.bash_logout`, `.bash_profile`, `.bashrc` and `.ksh` files. Matching on shell scripts with no extension
is not supported yet.
* isIgnoreFailures - Whether to allow the build to continue if there are warnings.
* isShowViolations - Whether rule violations are to be displayed on the console. Defaults to true.
* shellcheckVersion - By default "v0.7.1"
* severity - Minimum severity of errors to consider (error, warning, info, style). Defaults to `style`.
* useDocker - Whether to use docker image (true) or local shellcheck binary (false). Defaults to true.
* shellcheckBinary - /path/to/shellcheck binary. Defaults to `/usr/local/bin/shellcheck`. Ignored if useDocker is true.
* installer - for a machine without Docker or the shellcheck binary being installed, provide the installer to be used. It supports
the ones mentioned https://github.com/koalaman/shellcheck#installing[here] under the Unix family. By default, none. Ignored if useDocker is true.

[[sec:shellcheck_customize_xsl]]
== Customizing the HTML report

The HTML report generated by the Shellcheck task can be customized using a XSLT stylesheet, for example to highlight specific errors or change its appearance:

[source,kotlin]
----
tasks.withType<Shellcheck>().configureEach {
    reports {
        xml.isEnabled = false
        txt.isEnabled = false
        html.isEnabled = true
        html.stylesheet = resources.text.fromFile("config/xsl/shellcheck-custom.xsl")
    }
}
----

XML generated report comes from `shellcheck -f checkstyle`, therefore you can get inspiration from https://github.com/checkstyle/contribution/tree/master/xsl[a sample Checkstyle stylesheet.]

TXT generated report comes from `shellcheck -f tty`.

[[sec:shellcheck_testing]]
== Testing

With the addition of non Docker mode where a binary is supposed to be previously installed in the executing machine, we introduced a source
of non portability of the automated tests. To mitigate so, `ShellcheckBinaryPluginFuncTest` will be ignored unless an env var called
`SHELLCHECK_PATH` will be present.
