[[shellcheck_plugin]]
= The Shellcheck Plugin

The Shellcheck plugin performs quality checks on your project's Shell source files using https://github.com/koalaman/shellcheck[Shellcheck] and generates reports from these checks.


[[sec:shellcheck_usage]]
== Usage

To use the Shellcheck plugin, include the following in your build script:

.Using the Shellcheck plugin
[source,kotlin]
====
plugins {
    id("com.felipefzdz.gradle.shellcheck")
}
====

The plugin adds a task to the project called `shellcheck` that performs the quality checks.

Note that in order to be portable and repeatable Shellcheck will run:

* Through a Docker container
* A not-yet-configurable Shellcheck version, hardcoded at v0.7.1.

This implies that no dependencies are required on the executing machine, except for Docker itself.

[[sec:shellcheck_tasks]]
== Tasks

The Shellcheck plugin adds the following task to the project:

`shellcheck`

+
Runs Shellcheck against the provided Shell source files.


See the link:{groovyDslPath}/org.gradle.api.plugins.quality.ShellcheckExtension.html[ShellcheckExtension] class in the API documentation.


[[sec:shellcheck_extension]]
=== Extension

.Extension example
[source,kotlin]
====
shellcheck {
    shellScripts = file("src/shellScripts") // Folder where the shell scripts are located. It will search recursively matching `.sh` files. Further versions will enhance this functionality to allow other detection mechanisms (and to be cache incremental friendly)
    excludeErrors = listOf("SC1083", "SC2154") // Violations that are excluded from be taking in account.
    isIgnoreFailures = true // Whether to allow the build to continue if there are warnings.
    isShowViolations = true // Whether rule violations are to be displayed on the console. Defaults to true.
}
====

[[sec:shellcheck_customize_xsl]]
== Customizing the HTML report

The HTML report generated by the Shellcheck task can be customized using a XSLT stylesheet, for example to highlight specific errors or change its appearance:

.Customizing the HTML report
[source,kotlin]
====
tasks.withType<Shellcheck>().configureEach {
    reports {
        xml.isEnabled = false
        html.isEnabled = true
        html.stylesheet = resources.text.fromFile("config/xsl/shellcheck-custom.xsl")
    }
}
====

XML generated report comes from `shellcheck -f checkstyle`, therefore you can get inspiration from https://github.com/checkstyle/contribution/tree/master/xsl[a sample Checkstyle stylesheet.]
